// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// WorkerPoolConfigLister helps list WorkerPoolConfigs.
type WorkerPoolConfigLister interface {
	// List lists all WorkerPoolConfigs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.WorkerPoolConfig, err error)
	// WorkerPoolConfigs returns an object that can list and get WorkerPoolConfigs.
	WorkerPoolConfigs(namespace string) WorkerPoolConfigNamespaceLister
	WorkerPoolConfigListerExpansion
}

// workerPoolConfigLister implements the WorkerPoolConfigLister interface.
type workerPoolConfigLister struct {
	indexer cache.Indexer
}

// NewWorkerPoolConfigLister returns a new WorkerPoolConfigLister.
func NewWorkerPoolConfigLister(indexer cache.Indexer) WorkerPoolConfigLister {
	return &workerPoolConfigLister{indexer: indexer}
}

// List lists all WorkerPoolConfigs in the indexer.
func (s *workerPoolConfigLister) List(selector labels.Selector) (ret []*v1alpha1.WorkerPoolConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WorkerPoolConfig))
	})
	return ret, err
}

// WorkerPoolConfigs returns an object that can list and get WorkerPoolConfigs.
func (s *workerPoolConfigLister) WorkerPoolConfigs(namespace string) WorkerPoolConfigNamespaceLister {
	return workerPoolConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// WorkerPoolConfigNamespaceLister helps list and get WorkerPoolConfigs.
type WorkerPoolConfigNamespaceLister interface {
	// List lists all WorkerPoolConfigs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.WorkerPoolConfig, err error)
	// Get retrieves the WorkerPoolConfig from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.WorkerPoolConfig, error)
	WorkerPoolConfigNamespaceListerExpansion
}

// workerPoolConfigNamespaceLister implements the WorkerPoolConfigNamespaceLister
// interface.
type workerPoolConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all WorkerPoolConfigs in the indexer for a given namespace.
func (s workerPoolConfigNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.WorkerPoolConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WorkerPoolConfig))
	})
	return ret, err
}

// Get retrieves the WorkerPoolConfig from the indexer for a given namespace and name.
func (s workerPoolConfigNamespaceLister) Get(name string) (*v1alpha1.WorkerPoolConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("workerpoolconfig"), name)
	}
	return obj.(*v1alpha1.WorkerPoolConfig), nil
}
