// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	scheme "github.com/gardener/gardener/pkg/client/extensions/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkerPoolConfigsGetter has a method to return a WorkerPoolConfigInterface.
// A group's client should implement this interface.
type WorkerPoolConfigsGetter interface {
	WorkerPoolConfigs(namespace string) WorkerPoolConfigInterface
}

// WorkerPoolConfigInterface has methods to work with WorkerPoolConfig resources.
type WorkerPoolConfigInterface interface {
	Create(*v1alpha1.WorkerPoolConfig) (*v1alpha1.WorkerPoolConfig, error)
	Update(*v1alpha1.WorkerPoolConfig) (*v1alpha1.WorkerPoolConfig, error)
	UpdateStatus(*v1alpha1.WorkerPoolConfig) (*v1alpha1.WorkerPoolConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.WorkerPoolConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.WorkerPoolConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkerPoolConfig, err error)
	WorkerPoolConfigExpansion
}

// workerPoolConfigs implements WorkerPoolConfigInterface
type workerPoolConfigs struct {
	client rest.Interface
	ns     string
}

// newWorkerPoolConfigs returns a WorkerPoolConfigs
func newWorkerPoolConfigs(c *ExtensionsV1alpha1Client, namespace string) *workerPoolConfigs {
	return &workerPoolConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workerPoolConfig, and returns the corresponding workerPoolConfig object, and an error if there is any.
func (c *workerPoolConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkerPoolConfig, err error) {
	result = &v1alpha1.WorkerPoolConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkerPoolConfigs that match those selectors.
func (c *workerPoolConfigs) List(opts v1.ListOptions) (result *v1alpha1.WorkerPoolConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkerPoolConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workerPoolConfigs.
func (c *workerPoolConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a workerPoolConfig and creates it.  Returns the server's representation of the workerPoolConfig, and an error, if there is any.
func (c *workerPoolConfigs) Create(workerPoolConfig *v1alpha1.WorkerPoolConfig) (result *v1alpha1.WorkerPoolConfig, err error) {
	result = &v1alpha1.WorkerPoolConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		Body(workerPoolConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a workerPoolConfig and updates it. Returns the server's representation of the workerPoolConfig, and an error, if there is any.
func (c *workerPoolConfigs) Update(workerPoolConfig *v1alpha1.WorkerPoolConfig) (result *v1alpha1.WorkerPoolConfig, err error) {
	result = &v1alpha1.WorkerPoolConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		Name(workerPoolConfig.Name).
		Body(workerPoolConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *workerPoolConfigs) UpdateStatus(workerPoolConfig *v1alpha1.WorkerPoolConfig) (result *v1alpha1.WorkerPoolConfig, err error) {
	result = &v1alpha1.WorkerPoolConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		Name(workerPoolConfig.Name).
		SubResource("status").
		Body(workerPoolConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the workerPoolConfig and deletes it. Returns an error if one occurs.
func (c *workerPoolConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workerPoolConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched workerPoolConfig.
func (c *workerPoolConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkerPoolConfig, err error) {
	result = &v1alpha1.WorkerPoolConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workerpoolconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
