// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkerPools implements WorkerPoolInterface
type FakeWorkerPools struct {
	Fake *FakeExtensionsV1alpha1
	ns   string
}

var workerpoolsResource = schema.GroupVersionResource{Group: "extensions.gardener.cloud", Version: "v1alpha1", Resource: "workerpools"}

var workerpoolsKind = schema.GroupVersionKind{Group: "extensions.gardener.cloud", Version: "v1alpha1", Kind: "WorkerPool"}

// Get takes name of the workerPool, and returns the corresponding workerPool object, and an error if there is any.
func (c *FakeWorkerPools) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkerPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workerpoolsResource, c.ns, name), &v1alpha1.WorkerPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerPool), err
}

// List takes label and field selectors, and returns the list of WorkerPools that match those selectors.
func (c *FakeWorkerPools) List(opts v1.ListOptions) (result *v1alpha1.WorkerPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workerpoolsResource, workerpoolsKind, c.ns, opts), &v1alpha1.WorkerPoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkerPoolList{ListMeta: obj.(*v1alpha1.WorkerPoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkerPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workerPools.
func (c *FakeWorkerPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workerpoolsResource, c.ns, opts))

}

// Create takes the representation of a workerPool and creates it.  Returns the server's representation of the workerPool, and an error, if there is any.
func (c *FakeWorkerPools) Create(workerPool *v1alpha1.WorkerPool) (result *v1alpha1.WorkerPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workerpoolsResource, c.ns, workerPool), &v1alpha1.WorkerPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerPool), err
}

// Update takes the representation of a workerPool and updates it. Returns the server's representation of the workerPool, and an error, if there is any.
func (c *FakeWorkerPools) Update(workerPool *v1alpha1.WorkerPool) (result *v1alpha1.WorkerPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workerpoolsResource, c.ns, workerPool), &v1alpha1.WorkerPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerPool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkerPools) UpdateStatus(workerPool *v1alpha1.WorkerPool) (*v1alpha1.WorkerPool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workerpoolsResource, "status", c.ns, workerPool), &v1alpha1.WorkerPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerPool), err
}

// Delete takes name of the workerPool and deletes it. Returns an error if one occurs.
func (c *FakeWorkerPools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workerpoolsResource, c.ns, name), &v1alpha1.WorkerPool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkerPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workerpoolsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkerPoolList{})
	return err
}

// Patch applies the patch and returns the patched workerPool.
func (c *FakeWorkerPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkerPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workerpoolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkerPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerPool), err
}
